server:
  port: 8080

# database 연동 설정
spring:
  config:
    import: optional:application-secret.yml
  application:
    name: Capstone
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/join_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/ # thymeleaf 참조 경로
    suffix: .html
    check-template-location: 'true' # templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킴
    cache: false # thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          naver: #네이버 설정
            client-name: naver
            client-id: ${spring.security.oauth2.client.registration.naver.client-id}
            client-secret: ${spring.security.oauth2.client.registration.naver.client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google: #구글 설정
            client-name: google
            client-id: ${spring.security.oauth2.client.registration.google.client-id}
            client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider: #네이버 인증서버, 토큰 서버, 사용자 정보 발급 서버 등 설정해줌
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
